### ISSUE TITLE
[BUG] - Automatic export function does not work automatically

### ISSUE THREAD

**Issue by prorun26** [Lybron/health-auto-export#21]
Hi, unfortunately the auto export function does not work automatically. 

If I wait the set time interval until the message "Your automation has been executed" appears, the activity log shows the status "Succeeded" but no data arrives in my Home Assistant.

I tried it with an automation with the iOS app Shortcuts but the same problem here too. I get the message "Your automation has been executed" on my Lockscreen and inside the Auto Export app I can see in the activity log the status "Succeeded" but no data arrives in my Home Assistant.

If I open my automation directly in the Auto Export app and use the green export button, it works fine.

I use the iOS-App version 8.1.8 with iOS 17.4.1

**Comment by Lybron** [comment]
If you have a look at the v8.1.10 update now available, can you let me know if that helps with this issue?

[App Store Link](https://apple.co/3iqbU2d)

**Comment by prorun26** [comment]
When I use the Apple Shortcuts app to run my automation at a fixed time, I also have the same problem with the new version 8.1.10 of Auto Export. I get the message "Your automation has been executed", the activity log shows the status "Succeeded" but no data arrives in my Home Assistant.

Then I waited until the next automatic execution of the Auto Export automation and I got with the new version 8.1.10 another message in the lockscreen "Cache is updated with new data" and it worked fine.

I think if the automation is started via the Apple Shortcuts app, it will run but no new data from Apple Health will be loaded into the cache before.

**Comment by Lybron** [comment]
Hi @prorun26, following up on this bug report.

I released v8.1.11 about 2-3 weeks ago with some fixes, have you seen an improvement in syncing to your HA?

**Comment by buildingjoshbetter** [comment]
So I've been testing this for the past hour and it's still not fixed seems. For a top load I have to open up the app each individual time.

**Comment by Lybron** [comment]
@buildingjoshbetter is your automation for HA as well, otherwise could you share more details about how it is configured? Maybe you need to use a more frequent sync cadence?

See the relevant [limitations](https://help.healthyapps.dev/en/health-auto-export/automations) and you should ensure you have added the sync widget to your Home Screen.

With more details, I could provide more targeted troubleshooting steps.
